import { GroupCourseDetail } from "@/api/grup-course";
import { Section } from "@/api/sections";
import { Content } from "@/api/contents";

// Mock data untuk enrolled course detail
export const mockEnrolledCourseDetail: GroupCourseDetail = {
  id: "enrolled-course-1",
  idCourse: "course-123",
  title: "Complete Web Development Bootcamp 2024",
  kategori: "Programming",
  rating: 4.8,
  total_rating: 1250,
  id_teacher: "teacher-001",
  total_user: 3420,
  type_course: "Online",
  metode: "Self-paced with live sessions",
  jp: 120,
  silabus: "https://example.com/syllabus/web-dev-bootcamp.pdf",
  kuota: 5000,
  description: `
    <h2>Course Overview</h2>
    <p>Welcome to the Complete Web Development Bootcamp! This comprehensive course will take you from beginner to advanced level in modern web development.</p>
    
    <h3>What You'll Learn</h3>
    <ul>
      <li>HTML5, CSS3, and modern JavaScript (ES6+)</li>
      <li>React.js and Next.js for building modern web applications</li>
      <li>Node.js and Express for backend development</li>
      <li>Database design with PostgreSQL and MongoDB</li>
      <li>RESTful API design and GraphQL</li>
      <li>Authentication and Authorization</li>
      <li>Deployment and DevOps basics</li>
    </ul>

    <h3>Prerequisites</h3>
    <p>No prior programming experience required! Just bring your enthusiasm and commitment to learn.</p>

    <h3>Course Format</h3>
    <p>This course includes video lectures, hands-on projects, quizzes, and live coding sessions. You'll build 10+ real-world projects throughout the course.</p>
  `,
};

// Mock data untuk sections yang sudah dienroll
export const mockEnrolledSections: Section[] = [
  {
    id: "section-1",
    name: "Introduction to Web Development",
    description: "Get started with the fundamentals of web development",
    sequence: 1,
  },
  {
    id: "section-2",
    name: "HTML & CSS Fundamentals",
    description: "Master the building blocks of web pages",
    sequence: 2,
  },
  {
    id: "section-3",
    name: "JavaScript Essentials",
    description: "Learn modern JavaScript programming",
    sequence: 3,
  },
  {
    id: "section-4",
    name: "React.js Basics",
    description: "Build interactive user interfaces with React",
    sequence: 4,
  },
  {
    id: "section-5",
    name: "Next.js & Server-Side Rendering",
    description: "Create production-ready applications with Next.js",
    sequence: 5,
  },
  {
    id: "section-6",
    name: "Backend Development with Node.js",
    description: "Build scalable server-side applications",
    sequence: 6,
  },
  {
    id: "section-7",
    name: "Database Design & Management",
    description: "Work with SQL and NoSQL databases",
    sequence: 7,
  },
  {
    id: "section-8",
    name: "API Development",
    description: "Create RESTful APIs and GraphQL endpoints",
    sequence: 8,
  },
  {
    id: "section-9",
    name: "Authentication & Security",
    description: "Implement secure user authentication",
    sequence: 9,
  },
  {
    id: "section-10",
    name: "Deployment & DevOps",
    description: "Deploy your applications to production",
    sequence: 10,
  },
];

// Mock data untuk activities/contents di dalam sections
export const mockEnrolledActivities: Record<string, Content[]> = {
  "section-1": [
    {
      id: "content-1-1",
      type: "video",
      name: "Welcome to Web Development",
      description: "Introduction to the course and what you'll learn",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 1,
    },
    {
      id: "content-1-2",
      type: "pdf",
      name: "Course Syllabus",
      description: "Complete course outline and learning objectives",
      contentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 2,
    },
    {
      id: "content-1-3",
      type: "quiz",
      name: "Pre-Assessment Quiz",
      description: "Test your current knowledge level",
      contentUrl: "/quiz/pre-assessment",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 3,
    },
  ],
  "section-2": [
    {
      id: "content-2-1",
      type: "video",
      name: "HTML Basics",
      description: "Learn HTML tags, elements, and structure",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 1,
    },
    {
      id: "content-2-2",
      type: "video",
      name: "CSS Fundamentals",
      description: "Styling web pages with CSS",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 2,
    },
    {
      id: "content-2-3",
      type: "assignment",
      name: "Build Your First Web Page",
      description: "Create a personal portfolio page using HTML & CSS",
      contentUrl: "/assignment/first-webpage",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 3,
    },
    {
      id: "content-2-4",
      type: "document",
      name: "CSS Cheat Sheet",
      description: "Quick reference guide for CSS properties",
      contentUrl: "https://example.com/css-cheatsheet.pdf",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 4,
    },
  ],
  "section-3": [
    {
      id: "content-3-1",
      type: "video",
      name: "JavaScript Introduction",
      description: "Variables, data types, and operators",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 1,
    },
    {
      id: "content-3-2",
      type: "video",
      name: "Functions and Scope",
      description: "Master JavaScript functions",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 2,
    },
    {
      id: "content-3-3",
      type: "video",
      name: "Arrays and Objects",
      description: "Working with complex data structures",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 3,
    },
    {
      id: "content-3-4",
      type: "quiz",
      name: "JavaScript Fundamentals Quiz",
      description: "Test your JavaScript knowledge",
      contentUrl: "/quiz/js-fundamentals",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 4,
    },
  ],
  "section-4": [
    {
      id: "content-4-1",
      type: "video",
      name: "Introduction to React",
      description: "What is React and why use it?",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 1,
    },
    {
      id: "content-4-2",
      type: "video",
      name: "Components and Props",
      description: "Building reusable UI components",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 2,
    },
    {
      id: "content-4-3",
      type: "video",
      name: "State and Lifecycle",
      description: "Managing component state",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 3,
    },
    {
      id: "content-4-4",
      type: "assignment",
      name: "Build a Todo App",
      description: "Create a functional todo list with React",
      contentUrl: "/assignment/react-todo",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 4,
    },
  ],
  "section-5": [
    {
      id: "content-5-1",
      type: "video",
      name: "Next.js Overview",
      description: "Introduction to Next.js framework",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 1,
    },
    {
      id: "content-5-2",
      type: "video",
      name: "Server-Side Rendering",
      description: "Understanding SSR and SSG",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 2,
    },
    {
      id: "content-5-3",
      type: "document",
      name: "Next.js Best Practices",
      description: "Tips and tricks for Next.js development",
      contentUrl: "https://example.com/nextjs-best-practices.pdf",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 3,
    },
  ],
  "section-6": [
    {
      id: "content-6-1",
      type: "video",
      name: "Node.js Basics",
      description: "Introduction to server-side JavaScript",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 1,
    },
    {
      id: "content-6-2",
      type: "video",
      name: "Express.js Framework",
      description: "Building web servers with Express",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 2,
    },
    {
      id: "content-6-3",
      type: "assignment",
      name: "Build a REST API",
      description: "Create a RESTful API with Express",
      contentUrl: "/assignment/rest-api",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 3,
    },
  ],
  "section-7": [
    {
      id: "content-7-1",
      type: "video",
      name: "Database Fundamentals",
      description: "Introduction to databases",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 1,
    },
    {
      id: "content-7-2",
      type: "video",
      name: "SQL with PostgreSQL",
      description: "Working with relational databases",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 2,
    },
    {
      id: "content-7-3",
      type: "video",
      name: "MongoDB Basics",
      description: "NoSQL database with MongoDB",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 3,
    },
    {
      id: "content-7-4",
      type: "quiz",
      name: "Database Design Quiz",
      description: "Test your database knowledge",
      contentUrl: "/quiz/database-design",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 4,
    },
  ],
  "section-8": [
    {
      id: "content-8-1",
      type: "video",
      name: "RESTful API Design",
      description: "Best practices for API design",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 1,
    },
    {
      id: "content-8-2",
      type: "video",
      name: "GraphQL Introduction",
      description: "Modern API with GraphQL",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 2,
    },
    {
      id: "content-8-3",
      type: "document",
      name: "API Documentation Guide",
      description: "How to document your APIs",
      contentUrl: "https://example.com/api-docs-guide.pdf",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 3,
    },
  ],
  "section-9": [
    {
      id: "content-9-1",
      type: "video",
      name: "Authentication Basics",
      description: "Understanding authentication and authorization",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 1,
    },
    {
      id: "content-9-2",
      type: "video",
      name: "JWT and Sessions",
      description: "Implementing secure authentication",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 2,
    },
    {
      id: "content-9-3",
      type: "assignment",
      name: "Implement User Authentication",
      description: "Add login and registration to your app",
      contentUrl: "/assignment/user-auth",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 3,
    },
  ],
  "section-10": [
    {
      id: "content-10-1",
      type: "video",
      name: "Deployment Strategies",
      description: "How to deploy web applications",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 1,
    },
    {
      id: "content-10-2",
      type: "video",
      name: "CI/CD Pipeline",
      description: "Continuous integration and deployment",
      contentUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 2,
    },
    {
      id: "content-10-3",
      type: "document",
      name: "Production Checklist",
      description: "Things to check before going live",
      contentUrl: "https://example.com/production-checklist.pdf",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 3,
    },
    {
      id: "content-10-4",
      type: "assignment",
      name: "Final Project Deployment",
      description: "Deploy your complete application",
      contentUrl: "/assignment/final-deployment",
      contentStart: "2024-01-01T00:00:00Z",
      contentEnd: "2024-12-31T23:59:59Z",
      sequence: 4,
    },
  ],
};
